### PR TITLE
feat: add "focus workspace recent" command (#151)

### PR DESCRIPTION
**Pull request by kuznetsovvj**

### CODE REVIEW

**Comment by kuznetsovvj** [comment]
via #151

**Comment by kuznetsovvj** [comment]
@lars-berger If you tell me the default key combination for this command, I can update the readme file and the default config too

**Comment by lars-berger** [comment]
@kuznetsovvj Maybe `alt+r`?

Merged the other PR 👍 Thanks for these PRs - they're really solid

**Comment by kuznetsovvj** [comment]
@lars-berger thank you! what about default key for "workspace focus prev" and "workspace focus next"?

**Comment by lars-berger** [comment]
@kuznetsovvj hmm, how about `alt+t` for next and `alt+shift+t` for prev?

**Comment by kuznetsovvj** [comment]
Ok, i updated readme and default config

**Comment by lars-berger** [comment]
Awesome 💯 I'll try to get out a new 1.9 version at the end of the week

Also, I think I'll set up a Discord server soon so it gets easier to talk about development, ask questions etc

**Pull request merged**
