### PR TITLE
feat: Workspace keep alive based on user config

### PR DESCRIPTION
**Pull request by KiLLeRRaT**
I found a todo in the code, and thought I'd create a PR for it.

### CODE REVIEW

**Comment by KiLLeRRaT** [comment]
I just found that with the latest master, this no longer works, and it's related to the yaml deserializer.  It looks like it's not deserializing a bool properly anymore, it's treating it as a string, and when it comes to bind the config to the model, I get the below exception.  My config is also at the bottom.

Is there now a new way to deserialize and specify that the setting should be a `bool`?

```
Failed to parse user config. Invalid value at property: '$.workspaces[0].keep_alive'. System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $.workspaces[0].keep_alive | LineNumber: 0 | BytePositionInLine: 624.

 ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a boolean.

   at System.Text.Json.Utf8JsonReader.GetBoolean()

   at System.Text.Json.Serialization.Converters.BooleanConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)

   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)

   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)

   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)

   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)

   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)

   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)

   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)

   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)

   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

   --- End of inner exception stack trace ---

   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)

   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)

   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)

   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)

   at GlazeWM.Infrastructure.Serialization.JsonService.Deserialize[T](String json, List`1 converters) in C:\Projects.GitHub\GlazeWM\GlazeWM.Infrastructure\Serialization\JsonService.cs:line 31

   at GlazeWM.Infrastructure.Serialization.YamlService.Deserialize[T](String input, List`1 converters) in C:\Projects.GitHub\GlazeWM\GlazeWM.Infrastructure\Serialization\YamlService.cs:line 30

   at GlazeWM.Domain.UserConfigs.CommandHandlers.EvaluateUserConfigHandler.DeserializeUserConfig(String userConfigPath) in C:\Projects.GitHub\GlazeWM\GlazeWM.Domain\UserConfigs\CommandHandlers\EvaluateUserConfigHandler.cs:line 95

```

This is what my config looks like:
```yaml
workspaces:
  - name: 1
    display_name: "1"
    keep_alive: true
    bind_to_monitor: '\\.\DISPLAY1'
```

**Comment by KiLLeRRaT** [comment]
I've found the commit that this is happening on.

It's when we changed out Newtonsoft.Json.

`3f6eef5`

**Comment by lars-berger** [comment]
Good catch with the `Newtonsoft.Json` regression. Pushed a change to `master` with a fix

One minor correction is handling the edge case when a monitor is removed. When a monitor is removed, workspaces have to be moved off that monitor to another one. The below should work: 

```csharp
// RemoveMonitorHandler.cs
...
// Avoid moving empty workspaces.
var workspacesToMove = monitorToRemove.Children
  .Where(workspace => workspace.HasChildren() || workspace.KeepAlive)
  .Cast<Workspace>();
```

My bad for not being very active in this PR. I'd be happy to merge after the above change 👍

**Comment by KiLLeRRaT** [comment]
Hey @lars-berger thanks for sorting this out! Sorry I'm flat out here and was only going to look at this over the weekend! Appreciate the help :)

**Pull request merged**
